---

- import_tasks: check_vars.yml
  tags:
    - personal:check
    - check

- import_tasks: snap_install.yml
  tags:
    - personal:snap
    - snap
  when: personal_snap_packages is defined or personal_snap_classic_packages is defined

- import_tasks: package_install.yml
  tags:
    - admin:package
    - package
  when: personal_deb_packages is defined or personal_yum_packages is defined