---

- name: checking required variables are set
  assert:
    that: 
      - "{{ item }} is defined"
    fail_msg: "ERROR: {{ item }} is not defined"
  with_items:
    - "{{ required_variables }}"

- name: confirm required variables are set
  debug:
    msg: "SUCCESS: All required variables are defined"