---

- name: update deb packages
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
    upgrade: dist
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: update yum packages
  become: yes
  yum:
    name: "*"
    state: latest
    update_cache: yes
    autoremove: yes
  when: ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "CentOS"