---

- name: update deb packages
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
    upgrade: dist
  with_items:
    - "{{ admin_deb_packages }}"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: update yum packages
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    autoremove: yes
  with_items:
    - "{{ admin_yum_packages }}"
  when: ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "CentOS"