---

- name: install deb packages
  become: yes
  apt:
    name: "{{ admin_deb_packages }}"
    update_cache: yes
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
  when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu") and admin_deb_packages is defined

- name: install yum packages
  become: yes
  yum:
    name: "{{ admin_yum_packages }}"
    state: latest
    update_cache: yes
    autoremove: yes
  when: (ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "CentOS") and admin_yum_packages is defined