---

- name: install snap packages
  become: yes
  snap:
    name: "{{ item }}"
  with_items:
    - "{{ admin_snap_packages }}"
  when: admin_snap_packages is defined and admin_snap_packages != None

- name: install classic snap packages
  become: yes
  snap:
    name: "{{ item }}"
    state: present
    classic: yes
  with_items:
    - "{{ admin_snap_classic_packages }}"
  when: admin_snap_classic_packages is defined and admin_snap_classic_packages != None